services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montreal
      - VERSION=docker
      - PLEX_CLAIM=claim-SaeUJiKcQhcK95jzHNW1
    volumes:
      - /mnt/data/plex/config:/config
      - /mnt/data/plex/Media:/Media
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Montreal
    ports:
      - 5055:5055
    volumes:
      - /mnt/data/overseerr/config:/config
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montreal
      - AUTO_UPDATE=true
    volumes:
      - /mnt/data/jackett:/config
      - /mnt/data/download:/download
    ports:
      - 9117:9117
    restart: unless-stopped

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/Montreal
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montreal
    volumes:
      - /mnt/data/radarr:/config
      - /mnt/data/plex/Media:/Media
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montreal
    volumes:
      - /mnt/data/sonarr:/config
      - /mnt/data/plex/Media:/Media
    ports:
      - 8989:8989
    restart: unless-stopped
  
  transmission-openvpn:
    container_name: transmission-ovpn
    cap_add:
      - NET_ADMIN
    volumes:
      - /mnt/data/plex/Media:/Media
      - /mnt/data/transimission_openvpn/config:/config
    environment:
      - LOCAL_NETWORK=192.168.2.0/24
      - TRANSMISSION_SPEED_LIMIT_UP=0
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT=0
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=true
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=9999
      - TRANSMISSION_MAX_PEER_GLOBAL=99999
      - TRANSMISSION_PEER_LIMIT_GLOBAL=9999
      - TRANSMISSION_PEER_LIMIT_PER_TORRENT=9999
      - TRANSMISSION_DOWNLOAD_DIR=/Media/Torrent
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=false
      - TRANSMISSION_WEB_UI=transmission-web-control
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=ca_montreal
      - OPENVPN_USERNAME=p6341236
      - OPENVPN_PASSWORD=z5sG7WoyzF
    logging:
        driver: json-file
        options:
            max-size: 10m
    ports:
        - '9091:9091'
    image: haugene/transmission-openvpn:latest
    restart: unless-stopped