services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: 1.21.1
      TYPE: FABRIC
      MEMORY: 6G
      DIFFICULTY: hard
      MOTD: Server Pixelmon de Grêlien
      SPAWN_MONSTERS: false
      SERVER_NAME: Cobblemon Grêlien
      ENABLE_WHITELIST: true
      SERVER_PORT: 25565
    volumes:
      - /mnt/data/minecraft/server/cobblemon:/data